spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/digitalharbor_hospital?serverTimezone=UTC"
    username: "digitalharbor"
    password: "digitalharbor"
  servlet:
      timeout: 5s
  jpa:
    #hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true 

token : "d1g1t4lh4rb0r"

server:
  servlet:
    context-path: /hospital-dh-backend
  port: 8081